[debug] [2018-11-18T16:56:59.650Z] ----------------------------------------------------------------------
[debug] [2018-11-18T16:56:59.652Z] Command:       /usr/local/bin/node /usr/local/bin/firebase login
[debug] [2018-11-18T16:56:59.652Z] CLI Version:   6.1.0
[debug] [2018-11-18T16:56:59.652Z] Platform:      darwin
[debug] [2018-11-18T16:56:59.652Z] Node Version:  v8.10.0
[debug] [2018-11-18T16:56:59.652Z] Time:          Mon Nov 19 2018 00:56:59 GMT+0800 (CST)
[debug] [2018-11-18T16:56:59.653Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=866927757&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-11-18T16:57:37.393Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2018-11-18T16:58:52.818Z] Token Fetch Error: Error
    at new FirebaseError (/usr/local/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:28:31)
    at self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
